name: dynamic_json_form_builder
description: >
  A highly advanced, reusable, JSON-driven form builder for Flutter. Supports sections, all major field types (text, dropdown, date, slider, rating, color), custom theming, validation, conditional logic, and custom user-defined fields.
version: 1.2.0
homepage: https://github.com/chirag640/dynamic_json_form_builder
repository: https://github.com/chirag640/dynamic_json_form_builder
issue_tracker: https://github.com/chirag640/dynamic_json_form_builder/issues
documentation: https://github.com/chirag640/dynamic_json_form_builder#readme
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
# ...other dependencies...
keywords:
  - form
  - form-builder
  - json
  - dynamic
  - flutter
  - validation
  - theming
  - responsive
  - custom-fields
  - conditional-logic
dev_dependencies:
  flutter_test:
    sdk: flutter
  # Add lints, coverage, etc.
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  assets:
    - assets/

topics:
  - forms
  - json
  - dynamic
  - builder
  - flutter
